apiVersion: skaffold/v1
kind: Config
metadata:
  name: ftgo-application
build:
  artifacts:
  - image: msapatterns/ftgo-consumer-service
    context: ftgo-consumer-service
deploy:
  kubectl:
    manifests:
    - ops/deployment/kubernetes/cdc-services/eventuate-local-cdc-service.yml
    - ops/deployment/kubernetes/cdc-services/ftgo-tram-cdc-service.yml
    - ops/deployment/kubernetes/stateful-services/ftgo-db-secret.yml
    - ops/deployment/kubernetes/stateful-services/ftgo-dynamodb-local.yml
    - ops/deployment/kubernetes/stateful-services/ftgo-kafka-config.yml
    - ops/deployment/kubernetes/stateful-services/ftgo-kafka-deployment.yml
    - ops/deployment/kubernetes/stateful-services/ftgo-mysql-deployment.yml
    - ops/deployment/kubernetes/stateful-services/ftgo-zookeeper-deployment.yml
    - ops/ftgo-consumer-service/src/deployment/kubernetes/ftgo-consumer-service.yml
